import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Background, Controls, Position, ReactFlow, type Edge, type Node } from '@xyflow/react';
import '@xyflow/react/dist/style.css';
import { AlertCircle, ArrowRight, BrainCircuit, CheckCircle2, ChevronRight, Clock3, GitBranch, LoaderCircle, Network, Plus, Save, Sparkles } from 'lucide-react';
import './styles.css';

type Bible = { characters_present: string[]; emotional_tone: string; location: string };
type Scene = { scene_id: string; title: string; text: string; order: number; bible?: Bible };
type Audit = { scene_id: string; action: string; reason: string; hop: number; before_text?: string; after_text?: string };
type Version = { version_id: string; label: string; created_at: string; changed_scene_ids: string[]; audit: Audit[] };
type Story = { story_id:string; title:string; genre:string; logline:string; cover_gradient:string; scenes:Scene[]; dependencies: {source_scene_id:string;target_scene_id:string;kind:string;reason:string;confidence:number}[]; versions:Version[] };
type Summary = Pick<Story, 'story_id'|'title'|'genre'|'logline'|'cover_gradient'> & {scene_count:number};
const API = 'http://localhost:8000/api';

function App() {
  const [stories, setStories] = useState<Summary[]>([]); const [story, setStory] = useState<Story | null>(null);
  const [selected, setSelected] = useState('s06'); const [expandedStoryId, setExpandedStoryId] = useState<string | null>(null); const [storyScenes, setStoryScenes] = useState<Record<string, Scene[]>>({}); const [draft, setDraft] = useState(''); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false); const [status, setStatus] = useState(''); const [error, setError] = useState(''); const [create, setCreate] = useState(false);
  const scene = story?.scenes.find(s => s.scene_id === selected) ?? story?.scenes[0];
  const latest = story?.versions[story.versions.length - 1]; const audit = latest?.audit ?? [];
  const changed = new Set(latest?.changed_scene_ids ?? []);
  const selectedChange = audit.find(item => item.scene_id === scene?.scene_id && (item.action === 'regenerated' || item.action === 'edited'));
  const manuallyEdited = new Set(audit.filter(item => item.action === 'edited').map(item => item.scene_id));
  async function load(id?: string, sceneId?: string) { const list = await fetch(`${API}/stories`).then(r=>r.json()); setStories(list); const item = await fetch(`${API}/stories/${id ?? story?.story_id ?? list[0].story_id}`).then(r=>r.json()); setStory(item); setStoryScenes(current => ({...current, [item.story_id]: item.scenes})); setSelected(sceneId ?? item.scenes[0]?.scene_id); }
  async function toggleStory(storyId: string) { if (expandedStoryId === storyId) { setExpandedStoryId(null); return; } setExpandedStoryId(storyId); if (storyScenes[storyId]) return; try { const item = await fetch(`${API}/stories/${storyId}`).then(response => response.json()); setStoryScenes(current => ({...current, [storyId]: item.scenes})); } catch { setError('Could not load this story’s scene list.'); } }
  useEffect(()=>{ load().catch(()=>setError('Backend unavailable. Start the FastAPI server to begin.')); }, []);
  useEffect(()=>{ setDraft(scene?.text ?? ''); setEditing(false); }, [scene?.scene_id, scene?.text]);
  const nodes: Node[] = useMemo(()=> story?.scenes.map((s, i)=>({id:s.scene_id, position:{x:(i%5)*170,y:Math.floor(i/5)*130}, data:{label:<div><small>{s.scene_id.toUpperCase()}</small><strong>{s.title}</strong><span>{manuallyEdited.has(s.scene_id) ? 'Writer edited' : changed.has(s.scene_id) ? 'AI rewritten' : s.bible ? 'Mapped' : 'Not analyzed'}</span></div>}, className:`story-node ${selected===s.scene_id?'selected':''} ${changed.has(s.scene_id)?'changed':''}`, sourcePosition:Position.Right, targetPosition:Position.Left})) ?? [], [story, selected, latest]);
  const edges: Edge[] = useMemo(()=> story?.dependencies.map((d,i)=>({id:`e${i}`,source:d.source_scene_id,target:d.target_scene_id,label:d.kind,animated:changed.has(d.target_scene_id),style:{stroke:d.kind==='causal'?'#a78bfa':'#52607b'},labelStyle:{fill:'#c4b5fd',fontSize:9,fontWeight:600},labelBgStyle:{fill:'#181d30',fillOpacity:0.96,stroke:'#46336d',strokeWidth:1},labelBgPadding:[5,3],labelBgBorderRadius:5})) ?? [],[story, latest]);
  async function analyze() { if(!story) return; setBusy(true); setStatus(`Mapping ${story.scenes.length} scenes with OpenAI — usually 20–40 seconds.`); setError(''); try { const response=await fetch(`${API}/stories/${story.story_id}/analyze`,{method:'POST'}); if(!response.ok) throw new Error((await response.json()).detail); setStory(await response.json()); await load(story.story_id); } catch(e){setError(e instanceof Error?e.message:'Analysis failed');} finally{setBusy(false);setStatus('');} }
  async function saveEdit() { if(!story||!scene||draft===scene.text) return; setBusy(true); setStatus('Checking only graph-linked scenes and applying minimal AI rewrites…'); setError(''); try { const response=await fetch(`${API}/stories/${story.story_id}/scenes/${scene.scene_id}/edit`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:draft,label:`Writer edit — ${scene.title}`})}); if(!response.ok) throw new Error((await response.json()).detail); const next=await response.json(); setStory(next); } catch(e){setError(e instanceof Error?e.message:'Edit failed');} finally{setBusy(false);setStatus('');} }
  if (create) return <CreateStory onDone={(id)=>{setCreate(false);load(id)}} onCancel={()=>setCreate(false)} />;
  return <main><header><div className="brand"><div className="brand-mark"><GitBranch size={19}/></div><span>STORYTIME</span><b>Machine</b></div><div className="header-actions"><span className="live"><i/> LIVE AI</span><button className="ghost" onClick={()=>setCreate(true)}><Plus size={16}/> New story</button><button className="avatar">AK</button></div></header>
    <section className="topbar"><div><span className="eyebrow">NARRATIVE VERSION CONTROL</span><h1>Every decision has a <em>timeline.</em></h1><p>Trace exactly what changes — and leave the rest of your story untouched.</p></div><button className="primary" onClick={analyze} disabled={busy||!story}>{busy?<LoaderCircle className="spin"/>:<BrainCircuit/>}{story?.scenes.every(s=>s.bible)?'Re-map story bible':'Map story with AI'}</button></section>
    <div className="layout"><aside><div className="panel-title"><span>YOUR STORIES</span><button onClick={()=>setCreate(true)}><Plus size={16}/></button></div>{stories.map(item=><div className={`story-entry ${story?.story_id===item.story_id?'active':''}`} key={item.story_id}><button className="story-card" onClick={()=>load(item.story_id)}><i style={{background:item.cover_gradient}}/><div><b>{item.title}</b><small>{item.genre} · {item.scene_count} scenes</small></div></button><button className={`story-expand ${expandedStoryId===item.story_id?'open':''}`} aria-label={`Show scenes for ${item.title}`} onClick={()=>toggleStory(item.story_id)}><ChevronRight size={16}/></button>{expandedStoryId===item.story_id&&<div className="story-scenes">{storyScenes[item.story_id] ? storyScenes[item.story_id].map(sceneItem=><button key={sceneItem.scene_id} className={story?.story_id===item.story_id&&selected===sceneItem.scene_id?'active':''} onClick={()=>load(item.story_id,sceneItem.scene_id)}><span>{String(sceneItem.order).padStart(2,'0')}</span>{sceneItem.title}</button>) : <small>Loading scenes…</small>}</div>}</div>)}</aside>
      <section className="workspace"><div className="story-head"><div><span className="genre">{story?.genre}</span><h2>{story?.title ?? 'Loading story...'}</h2><p>{story?.logline}</p></div><div className="version"><Clock3 size={15}/><span>{latest?.label ?? 'Original draft'}</span></div></div>
      {status&&<div className="status"><LoaderCircle className="spin" size={16}/>{status}</div>}{error&&<div className="error"><AlertCircle size={16}/>{error}</div>}<div className="graph"><div className="graph-label"><Network size={15}/> DEPENDENCY MAP <span>{story?.dependencies.length ?? 0} causal links</span></div><ReactFlow nodes={nodes} edges={edges} onNodeClick={(_,node)=>setSelected(node.id)} fitView><Controls/><Background gap={18} size={1}/></ReactFlow></div>
      <div className="editor-grid"><div className="scene-list"><div className="panel-title"><span>SCENES</span><small>{story?.scenes.length ?? 0}</small></div>{story?.scenes.map(s=><button key={s.scene_id} className={`${selected===s.scene_id?'active':''} ${changed.has(s.scene_id)?'rewritten':''}`} onClick={()=>setSelected(s.scene_id)}><span>{String(s.order).padStart(2,'0')}</span><div><b>{s.title}</b><small>{manuallyEdited.has(s.scene_id) ? 'Writer edited — view diff' : changed.has(s.scene_id) ? 'AI rewritten — view diff' : s.bible?.emotional_tone || 'Awaiting AI map'}</small></div>{changed.has(s.scene_id)&&<Sparkles size={14}/>}</button>)}</div>
      <div className="editor"><div className="editor-head"><div><span className="eyebrow">SCENE {scene?.order}</span><h3>{scene?.title}</h3></div>{(!selectedChange || editing) && <button className="primary small" disabled={busy||draft===scene?.text} onClick={saveEdit}>{busy?<LoaderCircle className="spin"/>:<Save size={15}/>} Save & propagate</button>}</div>{selectedChange && !editing ? <SceneDiff change={selectedChange} onEdit={()=>setEditing(true)} /> : <div><textarea value={draft} onChange={e=>setDraft(e.target.value)} /><div className="context"><span><b>Characters</b> {scene?.bible?.characters_present?.join(', ') || 'Map with AI'}</span><span><b>Location</b> {scene?.bible?.location || '—'}</span></div></div>}</div>
      <Impact audit={audit} onSelect={setSelected} /></div></section></div></main>;
}
function SceneDiff({change,onEdit}:{change:Audit;onEdit:()=>void}) { const manual = change.action === 'edited'; return <div className="scene-diff"><div className="diff-banner"><Sparkles size={15}/><div><b>{manual ? 'Your manual edit' : 'AI minimal rewrite'}</b><span>{change.reason}</span></div><button className="edit-again" onClick={onEdit}>Edit this scene again</button></div><div className="diff-columns"><div><label>BEFORE</label><p>{change.before_text}</p></div><div><label>AFTER</label><p>{change.after_text}</p></div></div><p className="diff-note">{manual ? 'This is the source change that started the propagation.' : 'This scene was updated to stay consistent with the manual upstream edit.'} You can edit this or any other scene again; each save creates a separate version.</p></div> }
function Impact({audit,onSelect}:{audit:Audit[];onSelect:(sceneId:string)=>void}) { return <div className="impact"><div className="panel-title"><span>CHANGE REVIEW</span><small>{audit.length ? `${audit.length} decisions` : 'No edits yet'}</small></div>{audit.length===0?<p className="empty">Edit a scene to see the precise blast radius, checks, and byte-level preservation decisions.</p>:audit.map((a,i)=><div className={`audit ${a.action}`} key={i}>{a.action==='regenerated'||a.action==='edited'?<Sparkles/>:a.action==='checked'?<CheckCircle2/>:<ArrowRight/>}<div><button className="audit-title" onClick={()=>onSelect(a.scene_id)}><b>{a.scene_id.toUpperCase()} · {a.action === 'edited' ? 'your edit' : a.action === 'regenerated' ? 'AI rewrite' : a.action}</b></button><p>{a.reason}</p>{a.before_text&&<button className="audit-diff" onClick={()=>onSelect(a.scene_id)}><span><label>OLD</label>{a.before_text}</span><span><label>NEW</label>{a.after_text}</span></button>}</div><small>HOP {a.hop}</small></div>)}</div> }
function CreateStory({onDone,onCancel}:{onDone:(id:string)=>void,onCancel:()=>void}) { const [title,setTitle]=useState('');const [genre,setGenre]=useState('');const [logline,setLogline]=useState('');const [text,setText]=useState('');const [error,setError]=useState(''); async function submit(){const scenes=text.split('\n\n').filter(Boolean).map((value,i)=>({title:`Scene ${i+1}`,text:value}));if(scenes.length<2)return setError('Add at least two scenes, separated by blank lines.');const r=await fetch(`${API}/stories`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,genre,logline,scenes})});if(!r.ok)return setError('Could not create story.');onDone((await r.json()).story_id)}return <main className="modal-page"><div className="create"><span className="eyebrow">NEW STORY</span><h1>Start a new timeline</h1><input placeholder="Story title" value={title} onChange={e=>setTitle(e.target.value)}/><input placeholder="Genre" value={genre} onChange={e=>setGenre(e.target.value)}/><input placeholder="One-line logline" value={logline} onChange={e=>setLogline(e.target.value)}/><textarea placeholder="Paste scenes here; separate each scene with a blank line." value={text} onChange={e=>setText(e.target.value)}/>{error&&<div className="error">{error}</div>}<div><button className="ghost" onClick={onCancel}>Cancel</button><button className="primary" onClick={submit}>Create timeline <ArrowRight size={16}/></button></div></div></main>}
createRoot(document.getElementById('root')!).render(<App/>);
